apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: java-demo
          image: mavishek/java-demo:latest
          ports:
            - containerPort: 8080

